<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductStock;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        //Clear old data
        Product::truncate();
        ProductStock::truncate();

        //Products with basic info
        $products = [
            [
                'name' => 'Red T-Shirt',
                'slug' => 'red-t-shirt',
                'description' => 'A bright red t-shirt made from 100% cotton.',
                'category_id' => 1,
                'price' => 499,
                'image' => 'https://placehold.co/400?text=Red+TeeShirt',
            ],
            [
                'name' => 'Blue Jeans',
                'slug' => 'blue-jeans',
                'description' => 'Classic blue jeans with a modern fit.',
                'category_id' => 2,
                'price' => 1199,
                'image' => 'https://placehold.co/400?text=Blue+Jeans',
            ],
            [
                'name' => 'Sneakers',
                'slug' => 'sneakers',
                'description' => 'Comfortable sneakers for everyday wear.',
                'category_id' => 3,
                'price' => 2199,
                'image' => 'https://placehold.co/400?text=Sneakers',
            ],
            [
                'name' => 'Leather Jacket',
                'slug' => 'leather-jacket',
                'description' => 'Stylish leather jacket for a trendy look.',
                'category_id' => 4,
                'price' => 4999,
                'image' => 'https://placehold.co/400?text=Leather+Jacket',
            ],
            [
                'name' => 'Wool Sweater',
                'slug' => 'wool-sweater',
                'description' => 'Warm wool sweater for chilly days.',
                'category_id' => 5,
                'price' => 1599,
                'image' => 'https://placehold.co/400?text=Wool+Sweater',
            ],
            [
                'name' => 'Running Shoes',
                'slug' => 'running-shoes',
                'description' => 'Lightweight running shoes for a comfortable stride.',
                'category_id' => 3,
                'price' => 2499,
                'image' => 'https://placehold.co/400?text=Running+Shoes',
            ],
            [
                'name' => 'Casual Shirt',
                'slug' => 'casual-shirt',
                'description' => 'Comfortable casual shirt for everyday wear.',
                'category_id' => 2,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Casual+Shirt',
            ],
            [
                'name' => 'Formal Pants',
                'slug' => 'formal-pants',
                'description' => 'Elegant formal pants for a polished look.',
                'category_id' => 4,
                'price' => 1299,
                'image' => 'https://placehold.co/400?text=Formal+Pants',
            ],
            [
                'name' => 'Winter Coat',
                'slug' => 'winter-coat',
                'description' => 'Warm winter coat to keep you cozy.',
                'category_id' => 4,
                'price' => 5999,
                'image' => 'https://placehold.co/400?text=Winter+Coat',
            ],
            [
                'name' => 'Sports Watch',
                'slug' => 'sports-watch',
                'description' => 'Durable sports watch for active lifestyles.',
                'category_id' => 5,
                'price' => 3499,
                'image' => 'https://placehold.co/400?text=Sports+Watch',
            ],
            [
                'name' => 'Sunglasses',
                'slug' => 'sunglasses',
                'description' => 'Stylish sunglasses for sunny days.',
                'category_id' => 5,
                'price' => 1299,
                'image' => 'https://placehold.co/400?text=Sunglasses',
            ],
            [
                'name' => 'Backpack',
                'slug' => 'backpack',
                'description' => 'Spacious backpack for everyday use.',
                'category_id' => 5,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Backpack',
            ],
            [
                'name' => 'Baseball Cap',
                'slug' => 'baseball-cap',
                'description' => 'Classic baseball cap for a casual look.',
                'category_id' => 5,
                'price' => 499,
                'image' => 'https://placehold.co/400?text=Baseball+Cap',
            ],
            [
                'name' => 'Flip Flops',
                'slug' => 'flip-flops',
                'description' => 'Comfortable flip flops for warm weather.',
                'category_id' => 5,
                'price' => 299,
                'image' => 'https://placehold.co/400?text=Flip+Flops',
            ],
            [
                'name' => 'Hiking Boots',
                'slug' => 'hiking-boots',
                'description' => 'Sturdy hiking boots for outdoor adventures.',
                'category_id' => 5,
                'price' => 2999,
                'image' => 'https://placehold.co/400?text=Hiking+Boots',
            ],
            [
                'name' => 'Graphic Hoodie',
                'slug' => 'graphic-hoodie',
                'description' => 'Stylish graphic hoodie for a trendy look.',
                'category_id' => 4,
                'price' => 1799,
                'image' => 'https://placehold.co/400?text=Graphic+Hoodie',
            ],
            [
                'name' => 'Denim Jacket',
                'slug' => 'denim-jacket',
                'description' => 'Classic denim jacket for a timeless look.',
                'category_id' => 4,
                'price' => 2499,
                'image' => 'https://placehold.co/400?text=Denim+Jacket',
            ],
            [
                'name' => 'Cargo Shorts',
                'slug' => 'cargo-shorts',
                'description' => 'Comfortable cargo shorts for warm weather.',
                'category_id' => 4,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Cargo+Shorts',
            ],
            [
                'name' => 'Wristband',
                'slug' => 'wristband',
                'description' => 'Stylish wristband for a sporty look.',
                'category_id' => 5,
                'price' => 199,
                'image' => 'https://placehold.co/400?text=Wristband',
            ],
            [
                'name' => 'Beanie',
                'slug' => 'beanie',
                'description' => 'Warm beanie for cold weather.',
                'category_id' => 5,
                'price' => 399,
                'image' => 'https://placehold.co/400?text=Beanie',
            ],
            [
                'name' => 'Running Shorts',
                'slug' => 'running-shorts',
                'description' => 'Lightweight running shorts for comfort.',
                'category_id' => 5,
                'price' => 699,
                'image' => 'https://placehold.co/400?text=Running+Shorts',
            ],
            [
                'name' => 'Yoga Pants',
                'slug' => 'yoga-pants',
                'description' => 'Flexible yoga pants for ultimate comfort.',
                'category_id' => 5,
                'price' => 1299,
                'image' => 'https://placehold.co/400?text=Yoga+Pants',
            ],
            [
                'name' => 'Cycling Jersey',
                'slug' => 'cycling-jersey',
                'description' => 'High-performance cycling jersey for avid cyclists.',
                'category_id' => 5,
                'price' => 1599,
                'image' => 'https://placehold.co/400?text=Cycling+Jersey',
            ],
            [
                'name' => 'Golf Polo',
                'slug' => 'golf-polo',
                'description' => 'Classic golf polo for a polished look.',
                'category_id' => 5,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Golf+Polo',
            ],
            [
                'name' => 'Swim Trunks',
                'slug' => 'swim-trunks',
                'description' => 'Stylish swim trunks for a day at the beach.',
                'category_id' => 5,
                'price' => 699,
                'image' => 'https://placehold.co/400?text=Swim+Trunks',
            ],
            [
                'name' => 'Tennis Racket',
                'slug' => 'tennis-racket',
                'description' => 'High-quality tennis racket for competitive play.',
                'category_id' => 5,
                'price' => 3499,
                'image' => 'https://placehold.co/400?text=Tennis+Racket',
            ],
            [
                'name' => 'Basketball',
                'slug' => 'basketball',
                'description' => 'Official size basketball for all ages.',
                'category_id' => 5,
                'price' => 999,
                'image' => 'https://placehold.co/400?text=Basketball',
            ],
            [
                'name' => 'Soccer Ball',
                'slug' => 'soccer-ball',
                'description' => 'High-quality soccer ball for practice and play.',
                'category_id' => 5,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Soccer+Ball',
            ],
            [
                'name' => 'Volleyball',
                'slug' => 'volleyball',
                'description' => 'Durable volleyball for indoor and outdoor play.',
                'category_id' => 5,
                'price' => 799,
                'image' => 'https://placehold.co/400?text=Volleyball',
            ],
            [
                'name' => 'Badminton Racket',
                'slug' => 'badminton-racket',
                'description' => 'Lightweight badminton racket for quick volleys.',
                'category_id' => 5,
                'price' => 1299,
                'image' => 'https://placehold.co/400?text=Badminton+Racket',
            ],
            [
                'name' => 'Table Tennis Paddle',
                'slug' => 'table-tennis-paddle',
                'description' => 'High-quality table tennis paddle for competitive play.',
                'category_id' => 5,
                'price' => 499,
                'image' => 'https://placehold.co/400?text=Table+Tennis+Paddle',
            ],
            [
                'name' => 'Golf Balls',
                'slug' => 'golf-balls',
                'description' => 'High-quality golf balls for accurate shots.',
                'category_id' => 5,
                'price' => 399,
                'image' => 'https://placehold.co/400?text=Golf+Balls',
            ],
            [
                'name' => 'Fishing Rod',
                'slug' => 'fishing-rod',
                'description' => 'Durable fishing rod for all anglers.',
                'category_id' => 4,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=Fishing+Rod',
            ],
            [
                'name' => 'Camping Tent',
                'slug' => 'camping-tent',
                'description' => 'Spacious camping tent for outdoor adventures.',
                'category_id' => 4,
                'price' => 4999,
                'image' => 'https://placehold.co/400?text=Camping+Tent',
            ],
            [
                'name' => 'Hiking Backpack',
                'slug' => 'hiking-backpack',
                'description' => 'Durable hiking backpack for all your gear.',
                'category_id' => 4,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=Hiking+Backpack',
            ], 
            [
                'name' => 'Portable Grill',
                'slug' => 'portable-grill',
                'description' => 'Compact portable grill for outdoor cooking.',
                'category_id' => 4,
                'price' => 3499,
                'image' => 'https://placehold.co/400?text=Portable+Grill',
            ],
            [
                'name' => 'Camping Chair',
                'slug' => 'camping-chair',
                'description' => 'Comfortable camping chair for outdoor relaxation.',
                'category_id' => 4,
                'price' => 799,
                'image' => 'https://placehold.co/400?text=Camping+Chair',
            ],
            [
                'name' => 'Outdoor Blanket',
                'slug' => 'outdoor-blanket',
                'description' => 'Cozy outdoor blanket for picnics and camping.',
                'category_id' => 4,
                'price' => 499,
                'image' => 'https://placehold.co/400?text=Outdoor+Blanket',
            ],
            [
                'name' => 'Fishing Tackle Box',
                'slug' => 'fishing-tackle-box',
                'description' => 'Durable fishing tackle box for all your gear.',
                'category_id' => 4,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Fishing+Tackle+Box',
            ],
            [
                'name' => 'Hiking Poles',
                'slug' => 'hiking-poles',
                'description' => 'Lightweight and durable hiking poles for stability.',
                'category_id' => 4,
                'price' => 1299,
                'image' => 'https://placehold.co/400?text=Hiking+Poles',
            ],
            [
                'name' => 'Portable Power Bank',
                'slug' => 'portable-power-bank',
                'description' => 'High-capacity portable power bank for charging devices on the go.',
                'category_id' => 5,
                'price' => 599,
                'image' => 'https://placehold.co/400?text=Portable+Power+Bank',
            ],
            [
                'name' => 'Travel Pillow',
                'slug' => 'travel-pillow',
                'description' => 'Comfortable travel pillow for long journeys.',
                'category_id' => 5,
                'price' => 399,
                'image' => 'https://placehold.co/400?text=Travel+Pillow',
            ],
            [
                'name' => 'Water Bottle',
                'slug' => 'water-bottle',
                'description' => 'Durable water bottle for hydration on the go.',
                'category_id' => 5,
                'price' => 299,
                'image' => 'https://placehold.co/400?text=Water+Bottle',
            ],
            [
                'name' => 'Insulated Cooler',
                'slug' => 'insulated-cooler',
                'description' => 'High-performance cooler for keeping food and drinks cold.',
                'category_id' => 5,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=Insulated+Cooler',
            ],
            [
                'name' => 'Multi-tool',
                'slug' => 'multi-tool',
                'description' => 'Versatile multi-tool for all your outdoor needs.',
                'category_id' => 5,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Multi-tool',
            ],
            [
                'name' => 'First Aid Kit',
                'slug' => 'first-aid-kit',
                'description' => 'Essential first aid kit for outdoor emergencies.',
                'category_id' => 5,
                'price' => 799,
                'image' => 'https://placehold.co/400?text=First+Aid+Kit',
            ],
            [
                'name' => 'Portable Speaker',
                'slug' => 'portable-speaker',
                'description' => 'Compact portable speaker for outdoor use.',
                'category_id' => 5,
                'price' => 1499,
                'image' => 'https://placehold.co/400?text=Portable+Speaker',
            ],
            [
                'name' => 'Bluetooth Headphones',
                'slug' => 'bluetooth-headphones',
                'description' => 'Wireless Bluetooth headphones with noise cancellation.',
                'category_id' => 5,
                'price' => 2499,
                'image' => 'https://placehold.co/400?text=Bluetooth+Headphones',
            ],
            [
                'name' => 'Smartphone Case',
                'slug' => 'smartphone-case',
                'description' => 'Durable smartphone case for protection on the go.',
                'category_id' => 5,
                'price' => 499,
                'image' => 'https://placehold.co/400?text=Smartphone+Case',
            ],
            [
                'name' => 'Laptop Sleeve',
                'slug' => 'laptop-sleeve',
                'description' => 'Protective laptop sleeve for on-the-go professionals.',
                'category_id' => 5,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Laptop+Sleeve',
            ],
            [
                'name' => 'Wireless Charger',
                'slug' => 'wireless-charger',
                'description' => 'Fast wireless charger for compatible devices.',
                'category_id' => 5,
                'price' => 1299,
                'image' => 'https://placehold.co/400?text=Wireless+Charger',
            ],
            [
                'name' => 'USB Flash Drive',
                'slug' => 'usb-flash-drive',
                'description' => 'Compact USB flash drive for data storage.',
                'category_id' => 5,
                'price' => 399,
                'image' => 'https://placehold.co/400?text=USB+Flash+Drive',
            ],
            [
                'name' => 'External Hard Drive',
                'slug' => 'external-hard-drive',
                'description' => 'High-capacity external hard drive for data storage.',
                'category_id' => 5,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=External+Hard+Drive',
            ],
            [
                'name' => 'Smartwatch',
                'slug' => 'smartwatch',
                'description' => 'Feature-rich smartwatch for fitness and connectivity.',
                'category_id' => 5,
                'price' => 3499,
                'image' => 'https://placehold.co/400?text=Smartwatch',
            ],
            [
                'name' => 'Fitness Tracker',
                'slug' => 'fitness-tracker',
                'description' => 'Advanced fitness tracker for health monitoring.',
                'category_id' => 5,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=Fitness+Tracker',
            ],
            [
                'name' => 'E-Reader',
                'slug' => 'e-reader',
                'description' => 'Portable e-reader for book lovers.',
                'category_id' => 5,
                'price' => 2999,
                'image' => 'https://placehold.co/400?text=E-Reader',
            ],
            [
                'name' => 'Digital Camera',
                'slug' => 'digital-camera',
                'description' => 'High-resolution digital camera for photography enthusiasts.',
                'category_id' => 5,
                'price' => 5999,
                'image' => 'https://placehold.co/400?text=Digital+Camera',
            ],
            [
                'name' => 'Action Camera',
                'slug' => 'action-camera',
                'description' => 'Compact action camera for adventure seekers.',
                'category_id' => 5,
                'price' => 3999,
                'image' => 'https://placehold.co/400?text=Action+Camera',
            ],
            [
                'name' => 'Drone',
                'slug' => 'drone',
                'description' => 'High-performance drone for aerial photography.',
                'category_id' => 5,
                'price' => 7999,
                'image' => 'https://placehold.co/400?text=Drone',
            ],
            [
                'name' => 'VR Headset',
                'slug' => 'vr-headset',
                'description' => 'Immersive VR headset for gaming and entertainment.',
                'category_id' => 5,
                'price' => 4999,
                'image' => 'https://placehold.co/400?text=VR+Headset',
            ],
            [
                'name' => 'Gaming Console',
                'slug' => 'gaming-console',
                'description' => 'Next-gen gaming console for immersive gameplay.',
                'category_id' => 5,
                'price' => 29999,
                'image' => 'https://placehold.co/400?text=Gaming+Console',
            ],
            [
                'name' => 'Wireless Mouse',
                'slug' => 'wireless-mouse',
                'description' => 'Ergonomic wireless mouse for comfortable navigation.',
                'category_id' => 5,
                'price' => 799,
                'image' => 'https://placehold.co/400?text=Wireless+Mouse',
            ],
            [
                'name' => 'Mechanical Keyboard',
                'slug' => 'mechanical-keyboard',
                'description' => 'High-quality mechanical keyboard for typing enthusiasts.',
                'category_id' => 5,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=Mechanical+Keyboard',
            ],
            [
                'name' => 'Monitor Stand',
                'slug' => 'monitor-stand',
                'description' => 'Ergonomic monitor stand for better viewing angles.',
                'category_id' => 5,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Monitor+Stand',
            ],
            [
                'name' => 'Desk Organizer',
                'slug' => 'desk-organizer',
                'description' => 'Stylish desk organizer for a clutter-free workspace.',
                'category_id' => 5,
                'price' => 499,
                'image' => 'https://placehold.co/400?text=Desk+Organizer',
            ],
            [
                'name' => 'Cable Management Sleeve',
                'slug' => 'cable-management-sleeve',
                'description' => 'Flexible cable management sleeve for a tidy setup.',
                'category_id' => 5,
                'price' => 299,
                'image' => 'https://placehold.co/400?text=Cable+Management+Sleeve',
            ],
            [
                'name' => 'Laptop Stand',
                'slug' => 'laptop-stand',
                'description' => 'Adjustable laptop stand for better ergonomics.',
                'category_id' => 5,
                'price' => 899,
                'image' => 'https://placehold.co/400?text=Laptop+Stand',
            ],
            [
                'name' => 'Portable Monitor',
                'slug' => 'portable-monitor',
                'description' => 'Compact portable monitor for on-the-go productivity.',
                'category_id' => 5,
                'price' => 4999,
                'image' => 'https://placehold.co/400?text=Portable+Monitor',
            ],
            [
                'name' => 'Webcam',
                'slug' => 'webcam',
                'description' => 'High-definition webcam for video conferencing.',
                'category_id' => 5,
                'price' => 1299,
                'image' => 'https://placehold.co/400?text=Webcam',
            ],       
            [
                'name' => 'Microphone',
                'slug' => 'microphone',
                'description' => 'Professional microphone for clear audio recording.',
                'category_id' => 5,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=Microphone',
            ],
            [
                'name' => 'Graphics Tablet',
                'slug' => 'graphics-tablet',
                'description' => 'High-precision graphics tablet for digital artists.',
                'category_id' => 5,
                'price' => 2499,
                'image' => 'https://placehold.co/400?text=Graphics+Tablet',
            ],
            [
                'name' => 'Drawing Pen',
                'slug' => 'drawing-pen',
                'description' => 'Precision drawing pen for artists and designers.',
                'category_id' => 5,
                'price' => 499,
                'image' => 'https://placehold.co/400?text=Drawing+Pen',
            ],
            [
                'name' => '3D Printer',
                'slug' => '3d-printer',
                'description' => 'High-resolution 3D printer for creative projects.',
                'category_id' => 5,
                'price' => 14999,
                'image' => 'https://placehold.co/400?text=3D+Printer',
            ], 
            [
                'name' => 'Smart Home Hub',
                'slug' => 'smart-home-hub',
                'description' => 'Central hub for smart home devices.',
                'category_id' => 5,
                'price' => 2499,
                'image' => 'https://placehold.co/400?text=Smart+Home+Hub',
            ],
            [
                'name' => 'Smart Light Bulb',
                'slug' => 'smart-light-bulb',
                'description' => 'Energy-efficient smart light bulb with adjustable brightness.',
                'category_id' => 5,
                'price' => 399,
                'image' => 'https://placehold.co/400?text=Smart+Light+Bulb',
            ],
            [
                'name' => 'Smart Thermostat',
                'slug' => 'smart-thermostat',
                'description' => 'Smart thermostat for efficient temperature control.',
                'category_id' => 5,
                'price' => 4999,
                'image' => 'https://placehold.co/400?text=Smart+Thermostat',
            ],
            [
                'name' => 'Smart Lock',
                'slug' => 'smart-lock',
                'description' => 'Smart lock for keyless home entry.',
                'category_id' => 5,
                'price' => 2999,
                'image' => 'https://placehold.co/400?text=Smart+Lock',
            ],
            [
                'name' => 'Smart Security Camera',
                'slug' => 'smart-security-camera',
                'description' => 'Smart security camera with motion detection.',
                'category_id' => 5,
                'price' => 3499,
                'image' => 'https://placehold.co/400?text=Smart+Security+Camera',
            ],  
            [
                'name' => 'Smart Smoke Detector',
                'slug' => 'smart-smoke-detector',
                'description' => 'Smart smoke detector with mobile alerts.',
                'category_id' => 5,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=Smart+Smoke+Detector',
            ],
            [
                'name' => 'Smart Plug',
                'slug' => 'smart-plug',
                'description' => 'Smart plug for remote control of devices.',
                'category_id' => 5,
                'price' => 499,
                'image' => 'https://placehold.co/400?text=Smart+Plug',
            ],
            [
                'name' => 'Smart Air Purifier',
                'slug' => 'smart-air-purifier',
                'description' => 'Smart air purifier with HEPA filtration.',
                'category_id' => 5,
                'price' => 3999,
                'image' => 'https://placehold.co/400?text=Smart+Air+Purifier',
            ],
            [
                'name' => 'Smart Coffee Maker',
                'slug' => 'smart-coffee-maker',
                'description' => 'Smart coffee maker with app control.',
                'category_id' => 5,
                'price' => 2499,
                'image' => 'https://placehold.co/400?text=Smart+Coffee+Maker',
            ],
            [
                'name' => 'Smart Refrigerator',
                'slug' => 'smart-refrigerator',
                'description' => 'Smart refrigerator with touch screen.',
                'category_id' => 5,
                'price' => 59999,
                'image' => 'https://placehold.co/400?text=Smart+Refrigerator',
            ],
            [
                'name' => 'Smart Washing Machine',
                'slug' => 'smart-washing-machine',
                'description' => 'Smart washing machine with AI-powered cycles.',
                'category_id' => 5,
                'price' => 39999,
                'image' => 'https://placehold.co/400?text=Smart+Washing+Machine',
            ],
            [
                'name' => 'Smart Oven',
                'slug' => 'smart-oven',
                'description' => 'Smart oven with voice control.',
                'category_id' => 5,
                'price' => 49999,
                'image' => 'https://placehold.co/400?text=Smart+Oven',
            ],
            [
                'name' => 'Smart Dishwasher',
                'slug' => 'smart-dishwasher',
                'description' => 'Smart dishwasher with energy-efficient cycles.',
                'category_id' => 5,
                'price' => 44999,
                'image' => 'https://placehold.co/400?text=Smart+Dishwasher',
            ],
            [
                'name' => 'Smart Vacuum Cleaner',
                'slug' => 'smart-vacuum-cleaner',
                'description' => 'Smart vacuum cleaner with automatic dirt detection.',
                'category_id' => 5,
                'price' => 29999,
                'image' => 'https://placehold.co/400?text=Smart+Vacuum+Cleaner',
            ],
            [
                'name' => 'Smart Air Conditioner',
                'slug' => 'smart-air-conditioner',
                'description' => 'Smart air conditioner with energy-saving features.',
                'category_id' => 5,
                'price' => 59999,
                'image' => 'https://placehold.co/400?text=Smart+Air+Conditioner',
            ],
            [
                'name' => 'Smart Heater',
                'slug' => 'smart-heater',
                'description' => 'Smart heater with adjustable temperature settings.',
                'category_id' => 5,
                'price' => 24999,
                'image' => 'https://placehold.co/400?text=Smart+Heater',
            ],
            [
                'name' => 'Smart Humidifier',
                'slug' => 'smart-humidifier',
                'description' => 'Smart humidifier with adjustable mist levels.',
                'category_id' => 5,
                'price' => 19999,
                'image' => 'https://placehold.co/400?text=Smart+Humidifier',
            ],
            [
                'name' => 'Smart Dehumidifier',
                'slug' => 'smart-dehumidifier',
                'description' => 'Smart dehumidifier with energy-efficient operation.',
                'category_id' => 5,
                'price' => 24999,
                'image' => 'https://placehold.co/400?text=Smart+Dehumidifier',
            ],
            [
                'name' => 'Smart Air Quality Monitor',
                'slug' => 'smart-air-quality-monitor',
                'description' => 'Smart air quality monitor with real-time feedback.',
                'category_id' => 5,
                'price' => 2999,
                'image' => 'https://placehold.co/400?text=Smart+Air+Quality+Monitor',
            ],
            [
                'name' => 'Smart Water Leak Detector',
                'slug' => 'smart-water-leak-detector',
                'description' => 'Smart water leak detector with mobile alerts.',
                'category_id' => 5,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=Smart+Water+Leak+Detector',
            ],
            [
                'name' => 'Smart Garage Door Opener',
                'slug' => 'smart-garage-door-opener',
                'description' => 'Smart garage door opener with remote access.',
                'category_id' => 5,
                'price' => 2999,
                'image' => 'https://placehold.co/400?text=Smart+Garage+Door+Opener',
            ],
            [
                'name' => 'Smart Irrigation System',
                'slug' => 'smart-irrigation-system',
                'description' => 'Smart irrigation system with weather-based scheduling.',
                'category_id' => 5,
                'price' => 3999,
                'image' => 'https://placehold.co/400?text=Smart+Irrigation+System',
            ],
            [
                'name' => 'Smart Pet Feeder',
                'slug' => 'smart-pet-feeder',
                'description' => 'Smart pet feeder with automatic portion control.',
                'category_id' => 5,
                'price' => 2499,
                'image' => 'https://placehold.co/400?text=Smart+Pet+Feeder',
            ],
            [
                'name' => 'Smart Pet Camera',
                'slug' => 'smart-pet-camera',
                'description' => 'Smart pet camera with live streaming and two-way audio.',
                'category_id' => 5,
                'price' => 3499,
                'image' => 'https://placehold.co/400?text=Smart+Pet+Camera',
            ],
            [
                'name' => 'Smart Pet Door',
                'slug' => 'smart-pet-door',
                'description' => 'Smart pet door with automatic locking and unlocking.',
                'category_id' => 5,
                'price' => 3999,
                'image' => 'https://placehold.co/400?text=Smart+Pet+Door',
            ],
            [
                'name' => 'Smart Pet Tracker',
                'slug' => 'smart-pet-tracker',
                'description' => 'Smart pet tracker with GPS and activity monitoring.',
                'category_id' => 5,
                'price' => 1999,
                'image' => 'https://placehold.co/400?text=Smart+Pet+Tracker',
            ],
            [
                'name' => 'Smart Plant Monitor',
                'slug' => 'smart-plant-monitor',
                'description' => 'Smart plant monitor with soil moisture sensing.',
                'category_id' => 5,
                'price' => 1499,
                'image' => 'https://placehold.co/400?text=Smart+Plant+Monitor',
            ],
        ];

        foreach ($products as $index => $data) {
            //Insert product
            $product = Product::create($data);

            //Insert default stock for that product (no variant)
            ProductStock::create([
                'product_id' => $product->id,
                'sku' => 'SKU-' . strtoupper(str_replace(' ', '-', $product->name)) . '-' . ($index + 1),
                'variant' => null,
                'price' => $product->price,
                'qty' => rand(3,10),
                'image' => $product->image,
                'status' => 'active',
            ]);
        }
    }
}
